### ISSUE TITLE
[Request] Forge/Neoforge version of this mod?

### ISSUE THREAD

**Issue by ClockworkCorvus** [wasabiwhisper/harmonia#2]
I use the odyssey suite (Cadmus, Prometheus, etc.) and Xaero's map mods together quite often, but I use forge/neoforge, so using this mod is kind of not an option for me at the moment.

**Comment by wasabiwhisper** [comment]
I might have left this open for too long. Is there a specific pack you use the Odyssey suite with (perhaps a custom pack)? 
If this is still a request I will have a look at it in the coming month. I have no Forge/NeoForge experience _yet_. (Although this will change soon since 1.21).

I would also like to point out that the newer versions of Cadmus integrate the Xaero's compat in the mod itself.

**Comment by cswimr** [comment]
I'm not the OP, but I've been following this issue for a while. I personally am developing a 1.20.1 forge modpack with some friends, and we would like to publish it. We use xaeros because it performs better than journeymap, but in order to publish the pack on Modrinth, we can not use the FTB suite. Cadmus and the rest of the related suite is the best alternative, but we've been waiting for xaeros compat to switch. This would be awesome for us, as it'll probably be ages before everything we use updates to 1.21.

**Comment by wasabiwhisper** [comment]
That is clear, well if that is the case I'll do my best coming week(s) to get you the forge version. In theory it should be doable since the Cadmus mod makes use of Architectury, I simply never tried such a setup so it might take some time.
